import { Geist, Geist_Mono, Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poppins",
});

export const metadata = {
	title: "Prodify",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={poppins.variable} data-theme="light" >
			<body>
				<NextAuthProvider>
					<Navbar></Navbar>

					<Toaster></Toaster>
    
                    <div className="w-9/12 mx-auto">{children}</div>
				
                
                
                </NextAuthProvider>
			</body>
		</html>
	);
}
