import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAuthProvider";
import Providers from "@/Providers/Providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-poppins",
});

export const metadata = {
	title: "Prodify",
	description: "Generated by create next app",
    icons:{
        icon: "/logofav.png"
    }
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={poppins.variable} data-theme="light">
			<body>
				<Providers>
					<div className="w-9/12 mx-auto">{children}</div>
				</Providers>
			</body>
		</html>
	);
}
